/* eslint-disable import/prefer-default-export */
export const PDP_ARABIC_VALUES_TRANSLATIONS = {
    name: 'اسم',
    color: 'اللون',
    sku: 'كود تعريف البضاعة',
    brand_name: 'اسم العلامة التجارية',
    gender: 'جنس',
    material: 'ثوب',
    dress_length: 'طول الثوب',
    heel_height: 'علو الكعب',
    heel_shape: 'شكل الكعب',
    leg_length: 'طول الساق',
    neck_line: 'خط العنق',
    skirt_length: 'طول التنورة',
    toe_shape: 'شكل مقدمة الحذاء',
    sleeve_length: 'طول الكم',
    product_height: 'ارتفاع المنتج',
    product_length: 'طول المنتج',
    product_width: 'عرض المنتج',
    alternate_name: 'أسم بديل',
    category: 'الفئة',
    subcategory: 'الأقسام الفرعية',
    occasion: 'مناسبات',
    upper_material: 'المادة العلوية',
    sole: 'غايه',
    fit: 'نحيف',
    bag_dimension: 'أبعاد الحقيبة',
    model_height: 'ارتفاع الموديل',
    model_wearing_size: 'نموذج يرتدي الحجم',
    bag_size: 'حجم الحقيبة',
    bag_style: 'نمط الحقيبة',
    fastener: 'قفل',
    neckline: 'خط العنق',
    trend: 'اتجاه',
    fashion_segment: 'قسم الموضة',
    unisex: 'للجنسين',
    sustainable_fashion: 'أزياء مستدامة',
};
