export const ACTION_PROMOTIONAL_CREDIT_ADMIN = "0";
export const ACTION_PROMOTIONAL_ORDER = "1";
export const ACTION_PROMOTIONAL_REWARD_14_DAYS = "10";
export const ACTION_PROMOTIONAL_REFUND = "11";

export const ACTION_TRANSACTIONAL_BALANCE_UPDATED = "1";
export const ACTION_TRANSACTIONAL_REFERRAL_ADDED = "2";
export const ACTION_TRANSACTIONAL_ORDER = "3";
export const ACTION_TRANSACTIONAL_REFUND = "4";
export const ACTION_TRANSACTIONAL_PAYMENT_REVERT = "5";
export const ALL_HISTORY_TYPE = "all";
export const TRANSACTIONAL_HISTORY_TYPE = "transactional";
export const PROMOTIONAL_HISTORY_TYPE = "promotional";
