version: '3.3'
services:
  app:
    build:
      context: .
    environment:
      - SERVER_PORT=80
      - CI=true
    ports:
      - 80:80
    networks:
      - default
networks:
  default:
    driver: bridge
