export const WOMENS_CLOTHING_SIZE = [
    {
        international:'XXS',
        UK:'6',
        EU:'34',
        US:'2',
        Chest:'84',
        Waist:'64',
        Hip:'90'
    },
    {
        international:'XS',
        UK:'8',
        EU:'36',
        US:'4',
        Chest:'88',
        Waist:'68',
        Hip:'94'
    },
    {
        international:'S',
        UK:'10',
        EU:'38',
        US:'6',
        Chest:'92',
        Waist:'72',
        Hip:'98'
    },
    {
        international:'M',
        UK:'12',
        EU:'40',
        US:'8',
        Chest:'96',
        Waist:'76',
        Hip:'102'
    },
    {
        international:'L',
        UK:'14',
        EU:'42',
        US:'10',
        Chest:'100',
        Waist:'80',
        Hip:'106'
    },
    {
        international:'XL',
        UK:'16',
        EU:'44',
        US:'12',
        Chest:'104',
        Waist:'84',
        Hip:'110'
    }
]

export const WOMENS_JEANS_SIZE = [
    {
        JEANS:'24',
        WAIST_CM:'64',
        WAIST_INCH:'25.25'
    },
    {
        JEANS:'25',
        WAIST_CM:'66',
        WAIST_INCH:'26.5'
    },
    {
        JEANS:'26',
        WAIST_CM:'69',
        WAIST_INCH:'27.25'
    },
    {
        JEANS:'27',
        WAIST_CM:'72',
        WAIST_INCH:'28.25'
    },
    {
        JEANS:'28',
        WAIST_CM:'74',
        WAIST_INCH:'29.25'
    },
    {
        JEANS:'29',
        WAIST_CM:'77',
        WAIST_INCH:'30.25'
    },
    {
        JEANS:'30',
        WAIST_CM:'79',
        WAIST_INCH:'31.25'
    },
    {
        JEANS:'31',
        WAIST_CM:'83',
        WAIST_INCH:'32.75'
    },
    {
        JEANS:'32',
        WAIST_CM:'87',
        WAIST_INCH:'34.25'
    },
    {
        JEANS:'33',
        WAIST_CM:'90',
        WAIST_INCH:'35.75'
    },
    {
        JEANS:'34',
        WAIST_CM:'96',
        WAIST_INCH:'37.75'
    }
]

export const WOMENS_SHOES_SIZE = [
    {
        EU:'35',
        US:'5',
        UK:'2'
    },
    {
        EU:'36',
        US:'6',
        UK:'3'
    },
    {
        EU:'37',
        US:'6.5',
        UK:'4'
    },
    {
        EU:'37.5',
        US:'7',
        UK:'4.5'
    },
    {
        EU:'38',
        US:'7.5',
        UK:'5'
    },
    {
        EU:'38.5',
        US:'8',
        UK:'5.5'
    },
    {
        EU:'39',
        US:'8.5',
        UK:'6'
    },
    {
        EU:'40',
        US:'9',
        UK:'7'
    },
    {
        EU:'41',
        US:'10',
        UK:'8'
    },
    {
        EU:'42',
        US:'10.5',
        UK:'9'
    },
    {
        EU:'42.5',
        US:'11',
        UK:'9.5'
    }
]